CachePolicyApiGw:
  Type: AWS::CloudFront::CachePolicy
  Properties:
    CachePolicyConfig:
      Name: !Sub ${RunEnvironment}-${Product}-${SubDomain}-CachePolicy-ApiGw
      DefaultTTL: 3600
      MinTTL: 0
      MaxTTL: 31536000
      ParametersInCacheKeyAndForwardedToOrigin:
        EnableAcceptEncodingBrotli: true
        EnableAcceptEncodingGzip: true
        QueryStringsConfig:
          QueryStringBehavior: all
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Authorization
        CookiesConfig:
          CookieBehavior: all
