WebsiteBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    BucketName: !Sub ${SubDomain}-${RunEnvironment}.${Domain}.${TLD}-${AWS::Region}
    AccessControl: Private
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    VersioningConfiguration:
      Status: Enabled

WebsiteBucketPolicy:
  Type: AWS::S3::BucketPolicy
  DependsOn: OAI
  Properties:
    Bucket: !Ref WebsiteBucket
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Sid: AlloWSSLRequestsOnly
          Effect: Deny
          Resource:
            - !Sub ${WebsiteBucket.Arn}
            - !Sub ${WebsiteBucket.Arn}/*
          Action: s3:*
          Condition:
            Bool:
              aws:SecureTransport: false
          Principal: '*'
        - Sid: AllowCloudFrontAccess
          Effect: Allow
          Resource: !Sub ${WebsiteBucket.Arn}/*
          Action: s3:GetObject
          Principal:
            AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAI}
        - Sid: AllowPublicBlocking
          Effect: Allow
          Resource:
            - !Sub ${WebsiteBucket.Arn}
            - !Sub ${WebsiteBucket.Arn}/*
          Principal: '*'
