DirectoryIndexFunction:
  Type: AWS::CloudFront::Function
  Properties:
    AutoPublish: true
    Name: !Sub DirectoryIndexes-${AWS::StackName}
    FunctionConfig:
      Comment: Add index.html to directory name
      Runtime: cloudfront-js-1.0
    FunctionCode: |
      function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // Redirect URLs that don't end in / to a url that ends in /
          if (!uri.includes('.') && !uri.endsWith('/')) {
              var response = {
                  statusCode: 302
                , statusDescription: 'Found'
                , headers: {
                      "location": { "value": uri + '/' }
                  }
              };
              return response;
          }

          // For URLs that end in /, append index.html
          if (uri.endsWith('/')) {
              request.uri += 'index.html';
          }
          return request;
      }
