SecureHeadersFunction:
  Type: AWS::CloudFront::Function
  Properties:
    AutoPublish: true
    Name: !Sub SecureHeaders-${AWS::StackName}
    FunctionConfig:
      Comment: HSTS secure headers
      Runtime: cloudfront-js-1.0
    FunctionCode: !Sub |
      function handler(event) {
          var response = event.response;
          var headers = response.headers;

          // Set HTTP security headers
          // Since JavaScript doesn't allow for hyphens in variable names, we use the dict["key"] notation
          headers['strict-transport-security'] = {
            value: 'max-age=31536000; includeSubdomains; preload'
          };
          headers['content-security-policy'] = {
            value: "default-src 'self'; object-src 'none'; frame-src 'self'; child-src 'self'; script-src 'self'; script-src-elem 'self' https://connect2.finicity.com/assets/sdk/finicity-connect.min.js 'unsafe-inline'; style-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://stackpath.bootstrapcdn.com; style-src-attr 'self'; font-src 'self' https://cdnjs.cloudflare.com https://stackpath.bootstrapcdn.com https://fonts.gstatic.com; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests; require-trusted-types-for 'script'"
          };
          headers['x-content-type-options'] = { value: 'nosniff'};
          headers['x-frame-options'] = {value: 'DENY'};
          headers['x-xss-protection'] = {value: '1; mode=block'};

          // Return the response to viewers
          return response;
      }
